### ISSUE TITLE
UnicodeDecodeError UTF-8 codecs.py

### ISSUE THREAD

**Issue by ghost** [LavaPower/PyWeb#3]
Bonjour 
Je débute en Python, et j'ai voulu tester votre projet que je trouvais interressant.
Le problème, c'est que j'ai des erreurs : 

```python
sudo python3 PyWeb.py
 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Traceback (most recent call last):
  File "PyWeb.py", line 29, in <module>
    main = MainWindow(url)
  File "/home/rudy/Documents/Programmation/Python/PyWeb/files/PyWeb_main.py", line 66, in __init__
    defall = fichier.read().split('\n')
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 13: invalid continuation byte
```

J'ai regardé sur internet, mais je n'ai rien trouvé qui correspond à cette erreur... 
Je suis sous Ubuntu 18.04 LTS et j'ai Python 3.6.5 . 
Pourriez-vous m'aider à résoudre ce problème ? 
Merci d'avance

**Comment by AlexisHuvier** [comment]
Bonjour à toi !
Tout d'abord, merci d'avoir voulu tester le projet. Ensuite, pour ton bug ça viendrait de l'encodage. Je vais voir plus en profondeur et je reviens vers toi

**Comment by AlexisHuvier** [comment]
Yo, je viens de me rendre compte que les fichiers langues n'avait un UTF8 valide, créant le bug d'encodage. J'ai fait un commit qui devrait résoudre ça, peux-tu confirmer ?

**Comment by ghost** [comment]
Bonjour
Super, je vais tester ça ce soir, et je te redis les résultats !
Merci beaucoup !

**Comment by AlexisHuvier** [comment]
Pas de problème.
Je te préviens juste que le site permettant d'informer si une MAJ est dispo et le site d'accueil est mort. Normalement d'ici ce soir il devrait être de retour mais on s'est jamais.
Je ferme l'issue :)
